### ISSUE TITLE
Ampersand symbol

### ISSUE THREAD

**Issue by jim-rosales** [tommygebru/bws-colmaracademy#4]
The ampersand symbol is a reserved character in HTML which is why it is highlighted in red in the line of code below. It is a reserved character since it is used to add other special characters via their [entity reference](https://developer.mozilla.org/en-US/docs/Glossary/Entity).

Considering this the way to correctly add an ampersand symbol is by replacing `&` with `&amp;`

https://github.com/tommygebru/colmaracademy/blob/1f55ee45c3ee9f58e5cb147dcc2ff6bc25a0bb72/index.html#L37

**Comment by tommygebru** [comment]
Nice catch Jim 👍
