### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [tommygebru/bws-colmaracademy#6]
Grade: Meets Expectations

Summary:
Tommy, congrats on finishing your capstone project! Overall you did an excellent job as I didn't see any errors in your project syntactically or structurally. You also implemented all the required specs for the project, and the responsiveness of your page was impressive as it adapted to every screen size I tested it in. 

The only issue I saw in your project I saw dealt with style/formatting as discussed in issue #2. Do consider reading this [article](https://www.granneman.com/webdev/coding/formatting-and-indenting-your-html/) as well that covers formatting for HTML for improving the readability of your code. 

I didn't see you use any of the following properties/pseudo classes so consider researching them to expand your CSS skills: [hover effects](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover), [transitions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions), https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

This [codepen](https://codepen.io/JacobStone/pen/GfLEn) showcases how you can use hover effects and transitions together!

**Comment by tommygebru** [comment]
Thanks again for the feedback Jim, of course i would have added flair had it been a requirement and provide a personal touch also thanks for the links 😸
